AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Local template
Globals:
  Function:
    Timeout: 10
Resources:
  TwitchFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: .
      Handler: lambda_dynamo_refapp.lambdas.handler.lambda_handler
      Environment:
        Variables:
          CLIENT_ID: FOO
          CLIENT_BAR: BAR
          DYNAMO_TABLE: CLIENT_BAR
          POWERTOOLS_LOG_LEVEL: INFO
          POWERTOOLS_SERVICE_NAME: twitch
